### ISSUE TITLE
About Weights

### ISSUE THREAD

**Issue by BoooXing** [Alina9/distillation-vilt#2]
Hi， I have tried to run your code，but the 'weights' document is missing，how can i get those documents，thanks a lot.

**Comment by Alina9** [comment]
Hi!

You can find weights here https://disk.yandex.ru/d/hU_kaAVfdebv3Q. Also you
can use "bert-base-uncased" for the Bert part of the model (like here
https://huggingface.co/bert-base-uncased).

пт, 18 мар. 2022 г. в 06:01, BoooXing ***@***.***>:
